# 출처

https://github.com/wikibook/machine-learning/tree/2.0/jupyter_notebook

#뉴런노드[실습]

### AND & OR GATE 신경망 구현

In [ ]:
import tensorflow as tf
import numpy as np

#노드 클래스 생성
class Node:
    def __init__(self):
        self.w = tf.Variable(tf.random.normal([2, 1]))
        self.b = tf.Variable(tf.random.normal([1, 1]))
        
    def __call__(self, x):
        return self.preds(x)
    
    def preds(self,x):
        # 순전파 (forward propagation)
        out = tf.matmul(x,self.w)
        out = tf.add(out, self.b)
        out = tf.nn.sigmoid(out)
        return out
        # y = w*x + b 에서, sigmoid(y) 씌운것과 같음
    
    def loss(self,y_pred, y):
        return tf.reduce_mean(tf.square(y_pred - y))
        # MSE |실제-예측|^2합
   
    def train(self, inputs, outputs, learning_rate):
        epochs = range(10000)
        for epoch in epochs:
            with tf.GradientTape() as t:
                current_loss = self.loss(self.preds(inputs), outputs)
                # 역전파 (back propagation)
                dW, db = t.gradient(current_loss, [self.w, self.b])
                self.w.assign_sub(learning_rate * dW)
                self.b.assign_sub(learning_rate * db)
                if epoch % 100==0:
                   print(self.w)
                   print(self.b)
               
        

In [ ]:
#AND 연산 학습, 테스트
# AND operation
inputs = tf.constant([[0.0,0.0], [0.0,1.0], [1.0,0.0], [1.0,1.0]])
outputs = tf.constant([[0.0], [0.0], [0.0], [1.0]])

node = Node()
# train
node.train(inputs, outputs, 0.01)
# test
assert node([[0.0,0.0]]).numpy()[0][0] < 0.5
assert node([[0.0,1.0]]).numpy()[0][0] < 0.5
assert node([[1.0,0.0]]).numpy()[0][0] < 0.5
assert node([[1.0,1.0]]).numpy()[0][0] >= 0.5

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.10676478],
       [ 0.167796  ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.363627]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.05432558],
       [ 0.21360776]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.3493836]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.0010334],
       [ 0.2600362]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.3363067]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.05259638],
       [0.3065989 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.3249346]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.10600169],
       [0.3527762 ]], dtype=float32)>
<tf.V

In [ ]:
#OR 연산 학습, 테스트
# OR operation
inputs = tf.constant([[0.0,0.0], [0.0,1.0], [1.0,0.0], [1.0,1.0]])
outputs = tf.constant([[0.0], [1.0], [1.0], [1.0]])

node = Node()
# train
node.train(inputs, outputs, 0.01)
# test
assert node([[0.0,0.0]]).numpy()[0][0] < 0.5
assert node([[0.0,1.0]]).numpy()[0][0] >= 0.5
assert node([[1.0,0.0]]).numpy()[0][0] >= 0.5
assert node([[1.0,1.0]]).numpy()[0][0] >= 0.5